# Generated by Django 4.2.30 on 2026-07-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('group_knockout', 'Group + Knockout')], default='round_robin', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('tennis', 'Tennis')], default='football', max_length=50),
        ),
    ]
