# Generated by Django 4.2.30 on 2026-07-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_format_tournament_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(default='football', max_length=100),
        ),
    ]
